-- Agregar campo estado_publico a la tabla proyectos


-- Actualizar proyectos existentes para que sean públicos
UPDATE `proyectos` SET `estado_publico` = 'A' WHERE `estado_publico` IS NULL;

-- Crear algunos proyectos de ejemplo para mostrar en el sitio web
INSERT INTO `proyectos` (
    `nombre`, `slug`, `cliente`, `tipo_proyecto`, `ubicacion`, `direccion`, 
    `fecha_inicio`, `fecha_finalizacion`, `presupuesto`, `mostrar_presupuesto`,
    `estado`, `descripcion_corta`, `descripcion_detallada`, 
    `caracteristicas_tecnicas`, `area_construida`, `materiales_principales`,
    `testimonio_cliente`, `nombre_cliente`, `destacado`, `estado_publico`,
    `meta_titulo`, `meta_descripcion`, `meta_keywords`
) VALUES 
(
    'Casa Familiar Las Condes',
    'casa-familiar-las-condes',
    'Familia González',
    'residencial',
    'Las Condes, Santiago',
    'Av. Las Condes 1234',
    '2024-01-15',
    '2024-08-30',
    45000000,
    1,
    'completado',
    'Hermosa casa familiar de 3 dormitorios con amplio jardín y piscina.',
    'Proyecto de construcción de casa familiar de 180m² en Las Condes. Incluye 3 dormitorios, 2 baños, living comedor integrado, cocina moderna, jardín con piscina y quincho. Construcción con materiales de primera calidad y terminaciones de lujo.',
    'Estructura de hormigón armado, muros de ladrillo, techumbre de tejas, piso flotante en dormitorios, cerámica en baños y cocina, ventanas de PVC con doble vidrio.',
    180.50,
    'Hormigón, Ladrillos, Tejas, PVC, Cerámica, Piso flotante',
    'Excelente trabajo, cumplieron con todos los plazos y la calidad superó nuestras expectativas. Recomendamos totalmente a NextLine.',
    'María González',
    1,
    'A',
    'Casa Familiar Las Condes - NextLine Constructor',
    'Casa familiar de 3 dormitorios construida en Las Condes. Proyecto completado con materiales de primera calidad.',
    'casa familiar, Las Condes, construcción residencial, dormitorios, piscina'
),
(
    'Edificio Comercial Providencia',
    'edificio-comercial-providencia',
    'Inmobiliaria Central',
    'comercial',
    'Providencia, Santiago',
    'Av. Providencia 5678',
    '2023-06-01',
    '2024-03-15',
    120000000,
    1,
    'completado',
    'Edificio comercial de 4 pisos con locales comerciales y oficinas.',
    'Construcción de edificio comercial de 4 pisos con 8 locales comerciales en planta baja y 12 oficinas en pisos superiores. Incluye estacionamientos subterráneos y sistema de climatización central.',
    'Estructura de hormigón armado, fachada de vidrio y aluminio, ascensor, sistema de climatización central, estacionamientos subterráneos.',
    850.00,
    'Hormigón armado, Vidrio templado, Aluminio, Acero, Ascensor',
    'Proyecto ejecutado con excelencia técnica y cumplimiento de plazos. La calidad constructiva es sobresaliente.',
    'Carlos Mendoza',
    1,
    'A',
    'Edificio Comercial Providencia - NextLine Constructor',
    'Edificio comercial de 4 pisos en Providencia con locales y oficinas. Proyecto completado exitosamente.',
    'edificio comercial, Providencia, oficinas, locales comerciales, construcción'
),
(
    'Ampliación Casa Ñuñoa',
    'ampliacion-casa-nunoa',
    'Familia Silva',
    'residencial',
    'Ñuñoa, Santiago',
    'Av. Irarrázaval 9012',
    '2024-03-01',
    '2024-07-15',
    25000000,
    1,
    'completado',
    'Ampliación de casa existente con nuevo dormitorio y baño.',
    'Ampliación de casa existente agregando un dormitorio principal con baño en suite, walk-in closet y terraza privada. Manteniendo la arquitectura original de la casa.',
    'Estructura de hormigón, muros de ladrillo, techumbre de zinc, baño con porcelanato, closet empotrado.',
    45.00,
    'Hormigón, Ladrillos, Zinc, Porcelanato, Madera',
    'La ampliación quedó perfecta, se integró muy bien con la casa original. Muy contentos con el resultado.',
    'Ana Silva',
    0,
    'A',
    'Ampliación Casa Ñuñoa - NextLine Constructor',
    'Ampliación de casa en Ñuñoa con nuevo dormitorio y baño. Proyecto completado exitosamente.',
    'ampliación casa, Ñuñoa, dormitorio, baño, construcción residencial'
),
(
    'Bodega Industrial Maipú',
    'bodega-industrial-maipu',
    'Logística del Sur',
    'industrial',
    'Maipú, Santiago',
    'Camino a Melipilla 3456',
    '2023-09-01',
    '2024-01-30',
    85000000,
    1,
    'completado',
    'Bodega industrial de 2000m² para almacenamiento y distribución.',
    'Construcción de bodega industrial de 2000m² con oficinas administrativas, estacionamientos para camiones y sistema de seguridad. Diseñada para almacenamiento y distribución de productos.',
    'Estructura metálica, muros de panel sandwich, piso de hormigón pulido, sistema de seguridad, oficinas administrativas.',
    2000.00,
    'Estructura metálica, Panel sandwich, Hormigón pulido, Acero',
    'Excelente construcción, cumplió con todos los requerimientos técnicos y de seguridad. Muy recomendable.',
    'Roberto Vargas',
    0,
    'A',
    'Bodega Industrial Maipú - NextLine Constructor',
    'Bodega industrial de 2000m² en Maipú para almacenamiento y distribución. Proyecto completado.',
    'bodega industrial, Maipú, almacenamiento, distribución, construcción industrial'
),
(
    'Remodelación Restaurante Bellavista',
    'remodelacion-restaurante-bellavista',
    'Restaurante El Buen Sabor',
    'comercial',
    'Bellavista, Santiago',
    'Pío Nono 7890',
    '2024-02-01',
    '2024-05-15',
    18000000,
    1,
    'completado',
    'Remodelación completa de restaurante con nueva cocina y comedor.',
    'Remodelación completa de restaurante incluyendo nueva cocina industrial, comedor ampliado, barra de tragos y terraza exterior. Diseño moderno y funcional.',
    'Cocina industrial, sistema de ventilación, piso antideslizante, iluminación LED, terraza con techo retráctil.',
    120.00,
    'Acero inoxidable, Cerámica antideslizante, LED, Madera, Vidrio',
    'La remodelación transformó completamente el restaurante. Los clientes están encantados con el nuevo ambiente.',
    'Patricia Morales',
    0,
    'A',
    'Remodelación Restaurante Bellavista - NextLine Constructor',
    'Remodelación completa de restaurante en Bellavista con nueva cocina y comedor. Proyecto completado.',
    'remodelación restaurante, Bellavista, cocina industrial, comedor, construcción comercial'
);
