-- Script para insertar servicios de construcción
-- Base de datos: nextline_pyme

-- Servicios de Construcción Residencial
INSERT INTO servicio (nombre, categoria_id, descripcionCorta, descripcionLarga, caracteristicas, beneficios, tiempo_estimado, garantia, precio_desde, precio_hasta, mostrar_precio, estado, orden, destacado, slug, foto) VALUES
('Casas Unifamiliares', 7, 'Construcción de viviendas unifamiliares desde cero con diseño personalizado', 'Construimos casas unifamiliares completamente personalizadas según tus necesidades. Desde el diseño arquitectónico hasta la entrega llave en mano, nos encargamos de todo el proceso constructivo con materiales de primera calidad y mano de obra especializada.', 'Estructura de hormigón armado\nTechado con materiales de primera calidad\nInstalaciones eléctricas y sanitarias completas\nTerminaciones de alta calidad\nAislamiento térmico y acústico', 'Vivienda propia personalizada\nInversión segura a largo plazo\nValorización de la propiedad\nComodidad y funcionalidad\nGarantía de calidad', '6 - 8 meses', '2 años', 15000000, 25000000, 'S', 'A', 1, 'S', 'casas-unifamiliares', 'lib/images/default-service.svg'),

('Edificios de Apartamentos', 7, 'Construcción de edificios residenciales multifamiliares', 'Desarrollamos edificios de apartamentos modernos y funcionales, optimizando espacios y maximizando la eficiencia energética. Incluye diseño arquitectónico, permisos municipales y construcción completa.', 'Estructura antisísmica\nSistemas de seguridad modernos\nAscensores y escaleras\nEstacionamientos subterráneos\nÁreas verdes comunes', 'Inversión inmobiliaria rentable\nEspacios optimizados\nTecnología moderna\nSeguridad y comodidad\nValorización garantizada', '12 - 18 meses', '3 años', 50000000, 150000000, 'S', 'A', 2, 'S', 'edificios-apartamentos', 'lib/images/default-service.svg'),

-- Servicios de Construcción Comercial
('Locales Comerciales', 2, 'Construcción y remodelación de locales comerciales modernos', 'Construimos locales comerciales adaptados a las necesidades específicas de tu negocio. Desde tiendas hasta restaurantes, creamos espacios funcionales y atractivos que potencian tu actividad comercial.', 'Diseño comercial funcional\nInstalaciones especializadas\nFachadas atractivas\nSistemas de ventilación\nIluminación comercial', 'Espacio comercial optimizado\nMayor atracción de clientes\nFuncionalidad empresarial\nValorización del local\nImagen profesional', '3 - 4 meses', '1 año', 8000000, 20000000, 'S', 'A', 3, 'N', 'locales-comerciales', 'lib/images/default-service.svg'),

('Edificios de Oficinas', 2, 'Construcción de edificios corporativos y torres de oficinas', 'Desarrollamos edificios de oficinas modernos con tecnología de punta, sistemas eficientes y diseño corporativo que proyecta profesionalismo y funcionalidad empresarial.', 'Estructura corporativa moderna\nSistemas de climatización\nAscensores de alta velocidad\nEstacionamientos amplios\nTecnología integrada', 'Imagen corporativa profesional\nEspacios de trabajo eficientes\nTecnología de punta\nValorización empresarial\nPrestigio comercial', '18 - 24 meses', '5 años', 80000000, 300000000, 'S', 'A', 4, 'S', 'edificios-oficinas', 'lib/images/default-service.svg'),

-- Servicios de Remodelaciones
('Remodelación de Cocinas', 3, 'Renovación completa de cocinas con diseño moderno y funcional', 'Transformamos tu cocina en un espacio moderno, funcional y hermoso. Incluye diseño, demolición, instalaciones nuevas y terminaciones de alta calidad con los mejores materiales del mercado.', 'Diseño de cocinas modernas\nInstalaciones eléctricas y de gas\nMuebles de cocina personalizados\nEncimeras de granito o cuarzo\nIluminación especializada', 'Cocina moderna y funcional\nMayor valor de la propiedad\nComodidad en la cocina\nDiseño personalizado\nCalidad premium', '4 - 6 semanas', '1 año', 2500000, 8000000, 'S', 'A', 5, 'N', 'remodelacion-cocinas', 'lib/images/default-service.svg'),

('Remodelación de Baños', 3, 'Modernización completa de baños con diseño contemporáneo', 'Renovamos tus baños con diseño contemporáneo, instalaciones modernas y materiales de primera calidad. Creamos espacios de relajación y funcionalidad en tu hogar.', 'Diseño de baños modernos\nInstalaciones sanitarias nuevas\nPisos y paredes premium\nGrifería de alta gama\nVentilación mejorada', 'Baño moderno y elegante\nMayor comodidad diaria\nValorización del hogar\nHigiene mejorada\nDiseño contemporáneo', '3 - 4 semanas', '1 año', 1800000, 5000000, 'S', 'A', 6, 'N', 'remodelacion-banos', 'lib/images/default-service.svg'),

-- Servicios de Ampliaciones
('Ampliación de Casas', 4, 'Extensión de viviendas agregando habitaciones o pisos', 'Ampliamos tu casa agregando habitaciones, pisos completos o espacios específicos. Mantenemos la armonía arquitectónica y optimizamos el uso del espacio disponible.', 'Ampliaciones estructurales\nIntegración arquitectónica\nInstalaciones nuevas\nTerminaciones consistentes\nPermisos municipales', 'Mayor espacio habitable\nValorización de la propiedad\nComodidad familiar\nInversión inteligente\nDiseño integrado', '2 - 4 meses', '2 años', 5000000, 15000000, 'S', 'A', 7, 'N', 'ampliacion-casas', 'lib/images/default-service.svg'),

('Ampliación de Oficinas', 4, 'Extensión de espacios de trabajo y oficinas', 'Ampliamos tus oficinas agregando salas de reuniones, espacios de trabajo o pisos completos. Optimizamos la funcionalidad y productividad de tu empresa.', 'Ampliaciones corporativas\nEspacios de trabajo optimizados\nInstalaciones empresariales\nDiseño funcional\nTecnología integrada', 'Mayor capacidad de trabajo\nMejor productividad\nImagen empresarial\nValorización del inmueble\nEspacios modernos', '3 - 5 meses', '2 años', 8000000, 25000000, 'S', 'A', 8, 'N', 'ampliacion-oficinas', 'lib/images/default-service.svg'),

-- Servicios Especializados (ID 8)
('Piscinas', 8, 'Construcción de piscinas residenciales y comerciales', 'Construimos piscinas de todos los tamaños y estilos. Desde piscinas familiares hasta complejos acuáticos comerciales, con tecnología moderna y sistemas de mantenimiento eficientes.', 'Piscinas de concreto armado\nSistemas de filtración modernos\nIluminación LED\nCalefacción solar\nSistemas de limpieza automática', 'Entretenimiento familiar\nValorización de la propiedad\nEjercicio y relajación\nDiseño personalizado\nTecnología moderna', '6 - 8 semanas', '2 años', 3500000, 12000000, 'S', 'A', 9, 'S', 'piscinas', 'lib/images/default-service.svg'),

('Quinchos y Parrillas', 8, 'Construcción de espacios de entretenimiento al aire libre', 'Construimos quinchos y parrillas personalizados para disfrutar al aire libre. Incluye diseño, construcción, instalaciones eléctricas y terminaciones de alta calidad.', 'Estructura resistente al clima\nParrilla integrada de acero inoxidable\nInstalaciones eléctricas\nMesones de trabajo\nIluminación especializada', 'Entretenimiento al aire libre\nValorización de la propiedad\nEspacio social familiar\nDiseño personalizado\nCalidad premium', '4 - 6 semanas', '2 años', 2800000, 8000000, 'S', 'A', 10, 'S', 'quinchos-parrillas', 'lib/images/default-service.svg'),

('Pavimentación', 8, 'Construcción de pavimentos en asfalto, concreto y adoquines', 'Realizamos pavimentación de estacionamientos, patios, caminos y accesos vehiculares. Trabajamos con asfalto, concreto estampado y adoquines según tus necesidades.', 'Pavimentos de asfalto\nConcreto estampado\nAdoquines decorativos\nDrenaje integrado\nAcabados especiales', 'Acceso vehicular seguro\nValorización de la propiedad\nDurabilidad a largo plazo\nDiseño personalizado\nMantenimiento mínimo', '2 - 3 semanas', '1 año', 1500000, 5000000, 'S', 'A', 11, 'N', 'pavimentacion', 'lib/images/default-service.svg'),

-- Instalaciones (ID 9)
('Instalaciones Eléctricas', 9, 'Sistemas eléctricos completos para viviendas y comercios', 'Instalamos sistemas eléctricos completos, modernos y seguros. Incluye cableado, tableros, iluminación especializada y sistemas de automatización para hogares inteligentes.', 'Cableado eléctrico moderno\nTableros de distribución\nIluminación LED\nSistemas de automatización\nInstalaciones especializadas', 'Seguridad eléctrica\nEficiencia energética\nTecnología moderna\nComodidad diaria\nAhorro en consumo', '1 - 2 semanas', '1 año', 800000, 3000000, 'S', 'A', 12, 'N', 'instalaciones-electricas', 'lib/images/default-service.svg'),

-- Servicios de Consultoría
('Asesoría en Proyectos', 5, 'Consultoría técnica y de diseño para proyectos constructivos', 'Brindamos asesoría técnica especializada para proyectos de construcción. Incluye evaluación de factibilidad, diseño preliminar, cálculo de costos y gestión de permisos.', 'Evaluación técnica\nDiseño preliminar\nCálculo de costos\nGestión de permisos\nSupervisión técnica', 'Proyecto bien planificado\nAhorro en costos\nCumplimiento normativo\nCalidad garantizada\nAsesoría especializada', '1 - 2 semanas', '6 meses', 500000, 2000000, 'S', 'A', 13, 'N', 'asesoria-proyectos', 'lib/images/default-service.svg'),

-- Permisos y Trámites (ID 11)
('Permisos Municipales', 11, 'Gestión completa de trámites y permisos municipales', 'Nos encargamos de todos los trámites y permisos municipales necesarios para tu proyecto. Incluye planos arquitectónicos, estudios técnicos y seguimiento del proceso.', 'Gestión de trámites\nPlanos arquitectónicos\nEstudios técnicos\nSeguimiento municipal\nDocumentación completa', 'Tramitación eficiente\nCumplimiento normativo\nAhorro de tiempo\nDocumentación correcta\nProceso garantizado', '2 - 4 semanas', '3 meses', 300000, 1500000, 'S', 'A', 14, 'N', 'permisos-municipales', 'lib/images/default-service.svg'),

-- Diseño y Arquitectura (ID 10)
('Diseño Arquitectónico', 10, 'Servicios de diseño arquitectónico y planos técnicos', 'Desarrollamos diseños arquitectónicos personalizados y planos técnicos detallados. Incluye diseño 3D, planos de construcción y especificaciones técnicas completas.', 'Diseño arquitectónico\nPlanos técnicos detallados\nModelado 3D\nEspecificaciones técnicas\nDiseño personalizado', 'Diseño profesional\nPlanos técnicos precisos\nVisualización 3D\nPersonalización completa\nCalidad arquitectónica', '2 - 3 semanas', '6 meses', 800000, 3000000, 'S', 'A', 15, 'N', 'diseno-arquitectonico', 'lib/images/default-service.svg');

-- Actualizar el orden de los servicios existentes para que no haya conflictos
UPDATE servicio SET orden = orden + 20 WHERE orden < 20 AND id NOT IN (SELECT id FROM servicio WHERE nombre IN ('Casas Unifamiliares', 'Edificios de Apartamentos', 'Locales Comerciales', 'Edificios de Oficinas', 'Remodelación de Cocinas', 'Remodelación de Baños', 'Ampliación de Casas', 'Ampliación de Oficinas', 'Piscinas', 'Quinchos y Parrillas', 'Pavimentación', 'Instalaciones Eléctricas', 'Asesoría en Proyectos', 'Permisos Municipales', 'Diseño Arquitectónico'));
