apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitasync-api
  labels:
    app: vitasync-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitasync-api
  template:
    metadata:
      labels:
        app: vitasync-api
    spec:
      containers:
        - name: vitasync-app
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 80
          env:
            - name: APP_BASE_URL
              value: "https://vitasync.cl"
            - name: DATABASE_HOSTNAME
              value: "10.79.240.3"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "nextline_pyme"
            - name: DATABASE_USERNAME
              value: "root"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vitasync-db
                  key: password

